### ISSUE TITLE
Plugin doesn't appear to work for oak trees

### ISSUE THREAD

**Issue by rhodso** [gorbb/QwickTree#12] opened 2018-07-25 09:28 UTC
Latest version plugin
MC: 1.13
Using Iron Axe to chop down Accacia trees work, but chopping down an oak tree doesn't

Console output:
07/25/2018 10:24:51 ERROR
10:24:51 Could not pass event BlockBreakEvent to QwickTree v2.2.5
Console 07/25/2018 10:24:51
10:24:51 org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1166) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchFieldError: SWAMPLAND
at uk.co.gorbb.qwicktree.chop.ChopAction.getLeafReach(ChopAction.java:512) ~[?:?]
at uk.co.gorbb.qwicktree.chop.ChopAction.leafSearch(ChopAction.java:290) ~[?:?]
at uk.co.gorbb.qwicktree.chop.ChopAction.check(ChopAction.java:102) ~[?:?]
at uk.co.gorbb.qwicktree.chop.ChopAction.go(ChopAction.java:78) ~[?:?]
at uk.co.gorbb.qwicktree.QTListener.blockEvent(QTListener.java:54) ~[?:?]
at uk.co.gorbb.qwicktree.QTListener.blockBreakEvent(QTListener.java:27) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
... 17 more

**Comment by gorbb** [comment] 2018-07-27 21:47
Hi rhodso,

Thanks for reporting this issue. I have identified the cause and pushed a fix for this in my latest commit.
This error is due to the updates in 1.13, which hasn't quite encompassed a complete backwards compatibility with previous versions. I have published a new version of QwickTree which is now pending approval and should be available soon.

Thanks again!

**Closed as completed by gorbb** 2018-07-27 21:47 UTC
